### PR TITLE
[WIP] directionality mock data: use lib

### PR DESCRIPTION
**Pull request by wiese**
The mock fixture name contained a language code which confused me and as
it provided nothing more than what an already installed lib (doing that
very same job on the server side) can perform, I think we should lose
it.

### CODE REVIEW

**Comment by wiese** [comment]
Just realized this uses a server type definition.

**Comment by bitPogo** [comment]
Just a reminder -> the directionalities of wb and this package are not the same, so we should keep this in mind

**Comment by wiese** [comment]
If this is something we need to keep in mind then not with regards to this change (dev mocks) but with regards to SSR (using the lib) vs the CSR (using mw goodness).

**Review by jakobw — APPROVED** [review]
lgtm. Is this still WIP?

**Comment by jakobw** [comment]
The valid question of "Why can we use a module whose type is only defined in `/server/`?" came up. I poked around and found out the following:
* we get no console output for `src/mockup-entry.ts` because it is excluded in `tsconfig.json`
* it gets built anyway because vue-cli's `serve` does not abort on errors thrown by typescript

**Comment by jakobw** [comment]
I found this out by conducting the following clever experiment:
I added these two lines to client-entry.ts
```ts
const derp: object = { foo: 'bar' };
console.log( derp.foo );
```
and got an error printed to stdout, but it got built anyway. Doing the same to mockup-entry.ts had the same effect minus the logging. Removing `mockup-entry.ts` from the `exclude` in `tsconfig.json` resulted in both entry files being treated equally.

**Comment by manicki** [comment]
re-submitted to Gerrit as https://gerrit.wikimedia.org/r/#/c/wikibase/termbox/+/485154

**Pull request closed without merging**
