### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by bitPogo**

### CODE REVIEW

**Comment by bitPogo** [comment]
- Do we want member ordering?

**Comment by wiese** [comment]
@bitPogo Mind explaining "member ordering"? Is that alphabetical ordering of object members you want to see in liniting?

**Comment by jakobw** [comment]
@wiese I think this is about https://palantir.github.io/tslint/rules/member-ordering/. I'm not the biggest fan, because I think it's nice to put e.g. a private method right below the public method that uses it, but I don't have strong feelings about it.

**Comment by bitPogo** [comment]
@jakobw +1

**Comment by wiese** [comment]
@jakobw Thanks for the pointer. So yes, enforcing of member ordering (as it reads on the can). With its many config options it's not out of the question that the order you fancy is achievable with it, so why not use it if it eliminates room for endless discussions. But could/should totally be a separate step instead of holding this back.
Will not vote as I did not try yet.

**Comment by wiese** [comment]
@jakobw Thanks for the pointer. So yes, enforcing of member ordering (as it reads on the can). With its many config options it's not out of the question that the order you fancy is achievable with it, so why not use it if it eliminates room for endless discussions. But could/should totally be a separate step instead of holding this back.
Will not vote as I did not try yet.

**Pull request merged**
